{% set name = "bunqexport" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bunqexport-{{ version }}.tar.gz
  sha256: 1dd4cc8a937e109f22d534d7e3b58dc67e661ac0c665c8578c54f7ead46c245d

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - bunqexport = bunqexport.export:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bunq-sdk >=1.14.0,<2.0.0
    - pandas >=1.2.0,<2.0.0
    - python >={{ python_min }}

test:
  imports:
    - bunqexport
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stuertz/pybunqexport
  summary: Convert bunq payments to csv
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - step21
